#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

name: kokoro

on:
  push:
    paths:
      - kokoro/**
      - !kokoro/README.adoc
  schedule:
    - cron: 25 19 6 * *
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      model: kokoro
    secrets: inherit
